services:
  - type: web
    name: willenstest
    env: python
    buildCommand: ""
    startCommand: gunicorn willenstest.wsgi:application
    plan: free
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: willenstest.settings